version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  petstore:
    build:
      context: .
    hostname: petstore
    ports:
      - 9900:8080

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deployments/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9901:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./deployments/grafana/datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./deployments/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./deployments/grafana/petstore_requests_dashboard.json:/etc/grafana/provisioning/dashboards/petstore/requests_dashboard.json
      - ./deployments/grafana/config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 9902:3000

  trafficgen:
    build:
      context: deployments/trafficgen
